// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"time"

	"github.com/bartwork/home/contracts"
	"github.com/bartwork/home/contracts/dto"
	"github.com/bartwork/home/internal/transport/viewer"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
)

type loggerAuth struct {
	next contracts.Auth
}

func loggerMiddlewareAuth() MiddlewareAuth {
	return func(next contracts.Auth) contracts.Auth {
		return &loggerAuth{next: next}
	}
}

func (m loggerAuth) Login(ctx context.Context, login string, password string) (token string, user dto.User, err error) {
	logger := log.Ctx(ctx).With().Str("service", "Auth").Str("method", "login").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "auth.login",
				"request": viewer.Sprintf("%+v", requestAuthLogin{
					Login:    login,
					Password: password,
				}),
				"response": viewer.Sprintf("%+v", responseAuthLogin{
					Token: token,
					User:  user,
				}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call login")
			return
		}
		logger.Info().Func(logHandle).Msg("call login")
	}(time.Now())
	return m.next.Login(ctx, login, password)
}
