// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"github.com/bartwork/home/contracts"
	"github.com/gofiber/fiber/v2"
)

type httpAuth struct {
	errorHandler     ErrorHandler
	maxBatchSize     int
	maxParallelBatch int
	svc              *serverAuth
	base             contracts.Auth
}

func NewAuth(svcAuth contracts.Auth) (srv *httpAuth) {

	srv = &httpAuth{
		base: svcAuth,
		svc:  newServerAuth(svcAuth),
	}
	return
}

func (http *httpAuth) Service() *serverAuth {
	return http.svc
}

func (http *httpAuth) WithLog() *httpAuth {
	http.svc.WithLog()
	return http
}

func (http *httpAuth) WithMetrics() *httpAuth {
	http.svc.WithMetrics()
	return http
}

func (http *httpAuth) WithErrorHandler(handler ErrorHandler) *httpAuth {
	http.errorHandler = handler
	return http
}

func (http *httpAuth) SetRoutes(route *fiber.App) {
	route.Post("/api/v1/auth/login", http.serveLogin)
}
