// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"strconv"
	"time"

	"github.com/bartwork/home/contracts"
	"github.com/bartwork/home/contracts/dto"
	v2 "github.com/gofiber/fiber/v2"
)

type metricsAuth struct {
	next contracts.Auth
}

func metricsMiddlewareAuth(next contracts.Auth) contracts.Auth {
	return &metricsAuth{next: next}
}

func (m metricsAuth) Login(ctx context.Context, login string, password string) (token string, user dto.User, err error) {

	defer func(_begin time.Time) {
		var (
			success = true
			errCode int
		)
		if err != nil {
			success = false
			errCode = v2.StatusInternalServerError
			ec, ok := err.(withErrorCode)
			if ok {
				errCode = ec.Code()
			}
		}
		RequestCount.WithLabelValues("auth", "login", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestCountAll.WithLabelValues("auth", "login", strconv.FormatBool(success), strconv.Itoa(errCode)).Add(1)
		RequestLatency.WithLabelValues("auth", "login", strconv.FormatBool(success), strconv.Itoa(errCode)).Observe(time.Since(_begin).Seconds())
	}(time.Now())

	return m.next.Login(ctx, login, password)
}
