// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/gofiber/fiber/v2"
)

func (http *httpAuth) login(ctx context.Context, request requestAuthLogin) (response responseAuthLogin, err error) {

	response.Token, response.User, err = http.svc.Login(ctx, request.Login, request.Password)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpAuth) serveLogin(ctx *fiber.Ctx) (err error) {

	var request requestAuthLogin
	ctx.Response().SetStatusCode(200)
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	var response responseAuthLogin
	if response, err = http.login(ctx.UserContext(), request); err == nil {
		var iResponse interface{} = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ctx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
