// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import "github.com/bartwork/home/contracts/dto"

type requestAuthLogin struct {
	Login    string `json:"login,omitempty"`
	Password string `json:"password,omitempty"`
}

type responseAuthLogin struct {
	Token string   `json:"token,omitempty"`
	User  dto.User `json:"user,omitempty"`
}
