// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/bartwork/home/contracts"
	"github.com/bartwork/home/contracts/dto"
)

type serverAuth struct {
	svc   contracts.Auth
	login AuthLogin
}

type MiddlewareSetAuth interface {
	Wrap(m MiddlewareAuth)
	WrapLogin(m MiddlewareAuthLogin)

	WithMetrics()
	WithLog()
}

func newServerAuth(svc contracts.Auth) *serverAuth {
	return &serverAuth{
		login: svc.Login,
		svc:   svc,
	}
}

func (srv *serverAuth) Wrap(m MiddlewareAuth) {
	srv.svc = m(srv.svc)
	srv.login = srv.svc.Login
}

func (srv *serverAuth) Login(ctx context.Context, login string, password string) (token string, user dto.User, err error) {
	return srv.login(ctx, login, password)
}

func (srv *serverAuth) WrapLogin(m MiddlewareAuthLogin) {
	srv.login = m(srv.login)
}

func (srv *serverAuth) WithMetrics() {
	srv.Wrap(metricsMiddlewareAuth)
}

func (srv *serverAuth) WithLog() {
	srv.Wrap(loggerMiddlewareAuth())
}
