// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/bartwork/home/contracts"
	"github.com/bartwork/home/contracts/dto"
)

type AuthLogin func(ctx context.Context, login string, password string) (token string, user dto.User, err error)

type MiddlewareAuth func(next contracts.Auth) contracts.Auth

type MiddlewareAuthLogin func(next AuthLogin) AuthLogin
