// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"strconv"

	"github.com/gofiber/fiber/v2"
)

func (http *httpDevices) listDevices(ctx context.Context, request requestDevicesListDevices) (response responseDevicesListDevices, err error) {

	response.Devices, err = http.svc.ListDevices(ctx)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpDevices) serveListDevices(ctx *fiber.Ctx) (err error) {

	var request requestDevicesListDevices
	ctx.Response().SetStatusCode(200)

	var response responseDevicesListDevices
	if response, err = http.listDevices(ctx.UserContext(), request); err == nil {
		var iResponse interface{} = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ctx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
func (http *httpDevices) getDevice(ctx context.Context, request requestDevicesGetDevice) (response responseDevicesGetDevice, err error) {

	response.Device, err = http.svc.GetDevice(ctx, request.Id)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpDevices) serveGetDevice(ctx *fiber.Ctx) (err error) {

	var request requestDevicesGetDevice
	ctx.Response().SetStatusCode(200)

	if _id := ctx.Params("id"); _id != "" {
		var id int64
		id, err = strconv.ParseInt(_id, 10, 64)
		if err != nil {
			ctx.Status(fiber.StatusBadRequest)
			return sendResponse(ctx, "path arguments could not be decoded: "+err.Error())
		}
		request.Id = id
	}

	var response responseDevicesGetDevice
	if response, err = http.getDevice(ctx.UserContext(), request); err == nil {
		var iResponse interface{} = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ctx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
func (http *httpDevices) createDevice(ctx context.Context, request requestDevicesCreateDevice) (response responseDevicesCreateDevice, err error) {

	response.Device, err = http.svc.CreateDevice(ctx, request.Name, request.MqttTopic, request.DeviceType, request.Unit, request.Active)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpDevices) serveCreateDevice(ctx *fiber.Ctx) (err error) {

	var request requestDevicesCreateDevice
	ctx.Response().SetStatusCode(201)
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	var response responseDevicesCreateDevice
	if response, err = http.createDevice(ctx.UserContext(), request); err == nil {
		var iResponse interface{} = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ctx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
func (http *httpDevices) updateDevice(ctx context.Context, request requestDevicesUpdateDevice) (response responseDevicesUpdateDevice, err error) {

	response.Device, err = http.svc.UpdateDevice(ctx, request.Id, request.Name, request.MqttTopic, request.DeviceType, request.Unit, request.Active)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpDevices) serveUpdateDevice(ctx *fiber.Ctx) (err error) {

	var request requestDevicesUpdateDevice
	ctx.Response().SetStatusCode(200)
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	if _id := ctx.Params("id"); _id != "" {
		var id int64
		id, err = strconv.ParseInt(_id, 10, 64)
		if err != nil {
			ctx.Status(fiber.StatusBadRequest)
			return sendResponse(ctx, "path arguments could not be decoded: "+err.Error())
		}
		request.Id = id
	}

	var response responseDevicesUpdateDevice
	if response, err = http.updateDevice(ctx.UserContext(), request); err == nil {
		var iResponse interface{} = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ctx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
func (http *httpDevices) deleteDevice(ctx context.Context, request requestDevicesDeleteDevice) (response responseDevicesDeleteDevice, err error) {

	err = http.svc.DeleteDevice(ctx, request.Id)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpDevices) serveDeleteDevice(ctx *fiber.Ctx) (err error) {

	var request requestDevicesDeleteDevice
	ctx.Response().SetStatusCode(204)

	if _id := ctx.Params("id"); _id != "" {
		var id int64
		id, err = strconv.ParseInt(_id, 10, 64)
		if err != nil {
			ctx.Status(fiber.StatusBadRequest)
			return sendResponse(ctx, "path arguments could not be decoded: "+err.Error())
		}
		request.Id = id
	}

	var response responseDevicesDeleteDevice
	if response, err = http.deleteDevice(ctx.UserContext(), request); err == nil {
		var iResponse interface{} = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ctx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
