// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import "github.com/bartwork/home/contracts/dto"

// Formal exchange type, please do not delete.
type requestDevicesListDevices struct{}

type responseDevicesListDevices struct {
	Devices []dto.Device `json:"devices,omitempty"`
}

type requestDevicesGetDevice struct {
	Id int64 `json:"id,omitempty"`
}

type responseDevicesGetDevice struct {
	Device dto.Device `json:"device,omitempty"`
}

type requestDevicesCreateDevice struct {
	Name       string `json:"name,omitempty"`
	MqttTopic  string `json:"mqttTopic,omitempty"`
	DeviceType string `json:"deviceType,omitempty"`
	Unit       string `json:"unit,omitempty"`
	Active     bool   `json:"active,omitempty"`
}

type responseDevicesCreateDevice struct {
	Device dto.Device `json:"device,omitempty"`
}

type requestDevicesUpdateDevice struct {
	Id         int64  `json:"id,omitempty"`
	Name       string `json:"name,omitempty"`
	MqttTopic  string `json:"mqttTopic,omitempty"`
	DeviceType string `json:"deviceType,omitempty"`
	Unit       string `json:"unit,omitempty"`
	Active     bool   `json:"active,omitempty"`
}

type responseDevicesUpdateDevice struct {
	Device dto.Device `json:"device,omitempty"`
}

type requestDevicesDeleteDevice struct {
	Id int64 `json:"id,omitempty"`
}

// Formal exchange type, please do not delete.
type responseDevicesDeleteDevice struct{}
