// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/bartwork/home/contracts"
	"github.com/bartwork/home/contracts/dto"
)

type serverDevices struct {
	svc          contracts.Devices
	listDevices  DevicesListDevices
	getDevice    DevicesGetDevice
	createDevice DevicesCreateDevice
	updateDevice DevicesUpdateDevice
	deleteDevice DevicesDeleteDevice
}

type MiddlewareSetDevices interface {
	Wrap(m MiddlewareDevices)
	WrapListDevices(m MiddlewareDevicesListDevices)
	WrapGetDevice(m MiddlewareDevicesGetDevice)
	WrapCreateDevice(m MiddlewareDevicesCreateDevice)
	WrapUpdateDevice(m MiddlewareDevicesUpdateDevice)
	WrapDeleteDevice(m MiddlewareDevicesDeleteDevice)

	WithMetrics()
	WithLog()
}

func newServerDevices(svc contracts.Devices) *serverDevices {
	return &serverDevices{
		createDevice: svc.CreateDevice,
		deleteDevice: svc.DeleteDevice,
		getDevice:    svc.GetDevice,
		listDevices:  svc.ListDevices,
		svc:          svc,
		updateDevice: svc.UpdateDevice,
	}
}

func (srv *serverDevices) Wrap(m MiddlewareDevices) {
	srv.svc = m(srv.svc)
	srv.listDevices = srv.svc.ListDevices
	srv.getDevice = srv.svc.GetDevice
	srv.createDevice = srv.svc.CreateDevice
	srv.updateDevice = srv.svc.UpdateDevice
	srv.deleteDevice = srv.svc.DeleteDevice
}

func (srv *serverDevices) ListDevices(ctx context.Context) (devices []dto.Device, err error) {
	return srv.listDevices(ctx)
}

func (srv *serverDevices) GetDevice(ctx context.Context, id int64) (device dto.Device, err error) {
	return srv.getDevice(ctx, id)
}

func (srv *serverDevices) CreateDevice(ctx context.Context, name string, mqttTopic string, deviceType string, unit string, active bool) (device dto.Device, err error) {
	return srv.createDevice(ctx, name, mqttTopic, deviceType, unit, active)
}

func (srv *serverDevices) UpdateDevice(ctx context.Context, id int64, name string, mqttTopic string, deviceType string, unit string, active bool) (device dto.Device, err error) {
	return srv.updateDevice(ctx, id, name, mqttTopic, deviceType, unit, active)
}

func (srv *serverDevices) DeleteDevice(ctx context.Context, id int64) (err error) {
	return srv.deleteDevice(ctx, id)
}

func (srv *serverDevices) WrapListDevices(m MiddlewareDevicesListDevices) {
	srv.listDevices = m(srv.listDevices)
}

func (srv *serverDevices) WrapGetDevice(m MiddlewareDevicesGetDevice) {
	srv.getDevice = m(srv.getDevice)
}

func (srv *serverDevices) WrapCreateDevice(m MiddlewareDevicesCreateDevice) {
	srv.createDevice = m(srv.createDevice)
}

func (srv *serverDevices) WrapUpdateDevice(m MiddlewareDevicesUpdateDevice) {
	srv.updateDevice = m(srv.updateDevice)
}

func (srv *serverDevices) WrapDeleteDevice(m MiddlewareDevicesDeleteDevice) {
	srv.deleteDevice = m(srv.deleteDevice)
}

func (srv *serverDevices) WithMetrics() {
	srv.Wrap(metricsMiddlewareDevices)
}

func (srv *serverDevices) WithLog() {
	srv.Wrap(loggerMiddlewareDevices())
}
