// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/bartwork/home/contracts"
	"github.com/bartwork/home/contracts/dto"
)

type DevicesListDevices func(ctx context.Context) (devices []dto.Device, err error)
type DevicesGetDevice func(ctx context.Context, id int64) (device dto.Device, err error)
type DevicesCreateDevice func(ctx context.Context, name string, mqttTopic string, deviceType string, unit string, active bool) (device dto.Device, err error)
type DevicesUpdateDevice func(ctx context.Context, id int64, name string, mqttTopic string, deviceType string, unit string, active bool) (device dto.Device, err error)
type DevicesDeleteDevice func(ctx context.Context, id int64) (err error)

type MiddlewareDevices func(next contracts.Devices) contracts.Devices

type MiddlewareDevicesListDevices func(next DevicesListDevices) DevicesListDevices
type MiddlewareDevicesGetDevice func(next DevicesGetDevice) DevicesGetDevice
type MiddlewareDevicesCreateDevice func(next DevicesCreateDevice) DevicesCreateDevice
type MiddlewareDevicesUpdateDevice func(next DevicesUpdateDevice) DevicesUpdateDevice
type MiddlewareDevicesDeleteDevice func(next DevicesDeleteDevice) DevicesDeleteDevice
