// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"time"

	"github.com/bartwork/home/contracts"
	"github.com/bartwork/home/contracts/dto"
	"github.com/bartwork/home/internal/transport/viewer"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
)

type loggerDevices struct {
	next contracts.Devices
}

func loggerMiddlewareDevices() MiddlewareDevices {
	return func(next contracts.Devices) contracts.Devices {
		return &loggerDevices{next: next}
	}
}

func (m loggerDevices) ListDevices(ctx context.Context) (devices []dto.Device, err error) {
	logger := log.Ctx(ctx).With().Str("service", "Devices").Str("method", "listDevices").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "devices.listDevices",
				"request":  viewer.Sprintf("%+v", requestDevicesListDevices{}),
				"response": viewer.Sprintf("%+v", responseDevicesListDevices{Devices: devices}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call listDevices")
			return
		}
		logger.Info().Func(logHandle).Msg("call listDevices")
	}(time.Now())
	return m.next.ListDevices(ctx)
}

func (m loggerDevices) GetDevice(ctx context.Context, id int64) (device dto.Device, err error) {
	logger := log.Ctx(ctx).With().Str("service", "Devices").Str("method", "getDevice").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "devices.getDevice",
				"request":  viewer.Sprintf("%+v", requestDevicesGetDevice{Id: id}),
				"response": viewer.Sprintf("%+v", responseDevicesGetDevice{Device: device}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call getDevice")
			return
		}
		logger.Info().Func(logHandle).Msg("call getDevice")
	}(time.Now())
	return m.next.GetDevice(ctx, id)
}

func (m loggerDevices) CreateDevice(ctx context.Context, name string, mqttTopic string, deviceType string, unit string, active bool) (device dto.Device, err error) {
	logger := log.Ctx(ctx).With().Str("service", "Devices").Str("method", "createDevice").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "devices.createDevice",
				"request": viewer.Sprintf("%+v", requestDevicesCreateDevice{
					Active:     active,
					DeviceType: deviceType,
					MqttTopic:  mqttTopic,
					Name:       name,
					Unit:       unit,
				}),
				"response": viewer.Sprintf("%+v", responseDevicesCreateDevice{Device: device}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call createDevice")
			return
		}
		logger.Info().Func(logHandle).Msg("call createDevice")
	}(time.Now())
	return m.next.CreateDevice(ctx, name, mqttTopic, deviceType, unit, active)
}

func (m loggerDevices) UpdateDevice(ctx context.Context, id int64, name string, mqttTopic string, deviceType string, unit string, active bool) (device dto.Device, err error) {
	logger := log.Ctx(ctx).With().Str("service", "Devices").Str("method", "updateDevice").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "devices.updateDevice",
				"request": viewer.Sprintf("%+v", requestDevicesUpdateDevice{
					Active:     active,
					DeviceType: deviceType,
					Id:         id,
					MqttTopic:  mqttTopic,
					Name:       name,
					Unit:       unit,
				}),
				"response": viewer.Sprintf("%+v", responseDevicesUpdateDevice{Device: device}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call updateDevice")
			return
		}
		logger.Info().Func(logHandle).Msg("call updateDevice")
	}(time.Now())
	return m.next.UpdateDevice(ctx, id, name, mqttTopic, deviceType, unit, active)
}

func (m loggerDevices) DeleteDevice(ctx context.Context, id int64) (err error) {
	logger := log.Ctx(ctx).With().Str("service", "Devices").Str("method", "deleteDevice").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "devices.deleteDevice",
				"request":  viewer.Sprintf("%+v", requestDevicesDeleteDevice{Id: id}),
				"response": viewer.Sprintf("%+v", responseDevicesDeleteDevice{}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call deleteDevice")
			return
		}
		logger.Info().Func(logHandle).Msg("call deleteDevice")
	}(time.Now())
	return m.next.DeleteDevice(ctx, id)
}
