// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"github.com/bartwork/home/contracts"
	"github.com/gofiber/fiber/v2"
)

type httpDevices struct {
	errorHandler     ErrorHandler
	maxBatchSize     int
	maxParallelBatch int
	svc              *serverDevices
	base             contracts.Devices
}

func NewDevices(svcDevices contracts.Devices) (srv *httpDevices) {

	srv = &httpDevices{
		base: svcDevices,
		svc:  newServerDevices(svcDevices),
	}
	return
}

func (http *httpDevices) Service() *serverDevices {
	return http.svc
}

func (http *httpDevices) WithLog() *httpDevices {
	http.svc.WithLog()
	return http
}

func (http *httpDevices) WithMetrics() *httpDevices {
	http.svc.WithMetrics()
	return http
}

func (http *httpDevices) WithErrorHandler(handler ErrorHandler) *httpDevices {
	http.errorHandler = handler
	return http
}

func (http *httpDevices) SetRoutes(route *fiber.App) {
	route.Get("/api/v1/devices", http.serveListDevices)
	route.Get("/api/v1/devices/:id", http.serveGetDevice)
	route.Post("/api/v1/devices", http.serveCreateDevice)
	route.Put("/api/v1/devices/:id", http.serveUpdateDevice)
	route.Delete("/api/v1/devices/:id", http.serveDeleteDevice)
}
