// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/bartwork/home/contracts"
	"github.com/bartwork/home/contracts/dto"
)

type UsersListUsers func(ctx context.Context) (users []dto.User, err error)
type UsersGetUser func(ctx context.Context, id int64) (user dto.UserDetails, err error)

type MiddlewareUsers func(next contracts.Users) contracts.Users

type MiddlewareUsersListUsers func(next UsersListUsers) UsersListUsers
type MiddlewareUsersGetUser func(next UsersGetUser) UsersGetUser
