// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import "github.com/bartwork/home/contracts/dto"

// Formal exchange type, please do not delete.
type requestUsersListUsers struct{}

type responseUsersListUsers struct {
	Users []dto.User `json:"users,omitempty"`
}

type requestUsersGetUser struct {
	Id int64 `json:"id,omitempty"`
}

type responseUsersGetUser struct {
	User dto.UserDetails `json:"user,omitempty"`
}
