// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import "github.com/bartwork/home/contracts/dto"

// Formal exchange type, please do not delete.
type requestUsersListUsers struct{}

type responseUsersListUsers struct {
	Users []dto.User `json:"users,omitempty"`
}

type requestUsersGetUser struct {
	Id int64 `json:"id,omitempty"`
}

type responseUsersGetUser struct {
	User dto.User `json:"user,omitempty"`
}

type requestUsersCreateUser struct {
	In dto.CreateUser `json:"in,omitempty"`
}

type responseUsersCreateUser struct {
	User dto.User `json:"user,omitempty"`
}

type requestUsersUpdateUser struct {
	Id int64          `json:"id,omitempty"`
	In dto.UpdateUser `json:"in,omitempty"`
}

type responseUsersUpdateUser struct {
	User dto.User `json:"user,omitempty"`
}

type requestUsersDeleteUser struct {
	Id int64 `json:"id,omitempty"`
}

// Formal exchange type, please do not delete.
type responseUsersDeleteUser struct{}
