// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/bartwork/home/contracts"
	"github.com/bartwork/home/contracts/dto"
)

type serverUsers struct {
	svc       contracts.Users
	listUsers UsersListUsers
	getUser   UsersGetUser
}

type MiddlewareSetUsers interface {
	Wrap(m MiddlewareUsers)
	WrapListUsers(m MiddlewareUsersListUsers)
	WrapGetUser(m MiddlewareUsersGetUser)

	WithMetrics()
	WithLog()
}

func newServerUsers(svc contracts.Users) *serverUsers {
	return &serverUsers{
		getUser:   svc.GetUser,
		listUsers: svc.ListUsers,
		svc:       svc,
	}
}

func (srv *serverUsers) Wrap(m MiddlewareUsers) {
	srv.svc = m(srv.svc)
	srv.listUsers = srv.svc.ListUsers
	srv.getUser = srv.svc.GetUser
}

func (srv *serverUsers) ListUsers(ctx context.Context) (users []dto.User, err error) {
	return srv.listUsers(ctx)
}

func (srv *serverUsers) GetUser(ctx context.Context, id int64) (user dto.UserDetails, err error) {
	return srv.getUser(ctx, id)
}

func (srv *serverUsers) WrapListUsers(m MiddlewareUsersListUsers) {
	srv.listUsers = m(srv.listUsers)
}

func (srv *serverUsers) WrapGetUser(m MiddlewareUsersGetUser) {
	srv.getUser = m(srv.getUser)
}

func (srv *serverUsers) WithMetrics() {
	srv.Wrap(metricsMiddlewareUsers)
}

func (srv *serverUsers) WithLog() {
	srv.Wrap(loggerMiddlewareUsers())
}
