// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"strconv"

	"github.com/gofiber/fiber/v2"
)

func (http *httpUsers) listUsers(ctx context.Context, request requestUsersListUsers) (response responseUsersListUsers, err error) {

	response.Users, err = http.svc.ListUsers(ctx)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpUsers) serveListUsers(ctx *fiber.Ctx) (err error) {

	var request requestUsersListUsers
	ctx.Response().SetStatusCode(200)

	var response responseUsersListUsers
	if response, err = http.listUsers(ctx.UserContext(), request); err == nil {
		var iResponse interface{} = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ctx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
func (http *httpUsers) getUser(ctx context.Context, request requestUsersGetUser) (response responseUsersGetUser, err error) {

	response.User, err = http.svc.GetUser(ctx, request.Id)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpUsers) serveGetUser(ctx *fiber.Ctx) (err error) {

	var request requestUsersGetUser
	ctx.Response().SetStatusCode(200)

	if _id := ctx.Params("id"); _id != "" {
		var id int64
		id, err = strconv.ParseInt(_id, 10, 64)
		if err != nil {
			ctx.Status(fiber.StatusBadRequest)
			return sendResponse(ctx, "path arguments could not be decoded: "+err.Error())
		}
		request.Id = id
	}

	var response responseUsersGetUser
	if response, err = http.getUser(ctx.UserContext(), request); err == nil {
		var iResponse interface{} = response
		if redirect, ok := iResponse.(withRedirect); ok {
			return ctx.Redirect(redirect.RedirectTo())
		}

		return sendResponse(ctx, response)
	}
	if errCoder, ok := err.(withErrorCode); ok {
		ctx.Status(errCoder.Code())
	} else {
		ctx.Status(fiber.StatusInternalServerError)
	}
	return sendResponse(ctx, err)
}
