// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"github.com/bartwork/home/contracts"
	"github.com/gofiber/fiber/v2"
)

type httpUsers struct {
	errorHandler     ErrorHandler
	maxBatchSize     int
	maxParallelBatch int
	svc              *serverUsers
	base             contracts.Users
}

func NewUsers(svcUsers contracts.Users) (srv *httpUsers) {

	srv = &httpUsers{
		base: svcUsers,
		svc:  newServerUsers(svcUsers),
	}
	return
}

func (http *httpUsers) Service() *serverUsers {
	return http.svc
}

func (http *httpUsers) WithLog() *httpUsers {
	http.svc.WithLog()
	return http
}

func (http *httpUsers) WithMetrics() *httpUsers {
	http.svc.WithMetrics()
	return http
}

func (http *httpUsers) WithErrorHandler(handler ErrorHandler) *httpUsers {
	http.errorHandler = handler
	return http
}

func (http *httpUsers) SetRoutes(route *fiber.App) {
	route.Get("/api/v1/users", http.serveListUsers)
	route.Get("/api/v1/users/:id", http.serveGetUser)
	route.Post("/api/v1/users", http.serveCreateUser)
	route.Put("/api/v1/users/:id", http.serveUpdateUser)
	route.Delete("/api/v1/users/:id", http.serveDeleteUser)
}
