// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"time"

	"github.com/bartwork/home/contracts"
	"github.com/bartwork/home/contracts/dto"
	"github.com/bartwork/home/internal/transport/viewer"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
)

type loggerUsers struct {
	next contracts.Users
}

func loggerMiddlewareUsers() MiddlewareUsers {
	return func(next contracts.Users) contracts.Users {
		return &loggerUsers{next: next}
	}
}

func (m loggerUsers) ListUsers(ctx context.Context) (users []dto.User, err error) {
	logger := log.Ctx(ctx).With().Str("service", "Users").Str("method", "listUsers").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "users.listUsers",
				"request":  viewer.Sprintf("%+v", requestUsersListUsers{}),
				"response": viewer.Sprintf("%+v", responseUsersListUsers{Users: users}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call listUsers")
			return
		}
		logger.Info().Func(logHandle).Msg("call listUsers")
	}(time.Now())
	return m.next.ListUsers(ctx)
}

func (m loggerUsers) GetUser(ctx context.Context, id int64) (user dto.User, err error) {
	logger := log.Ctx(ctx).With().Str("service", "Users").Str("method", "getUser").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "users.getUser",
				"request":  viewer.Sprintf("%+v", requestUsersGetUser{Id: id}),
				"response": viewer.Sprintf("%+v", responseUsersGetUser{User: user}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call getUser")
			return
		}
		logger.Info().Func(logHandle).Msg("call getUser")
	}(time.Now())
	return m.next.GetUser(ctx, id)
}

func (m loggerUsers) CreateUser(ctx context.Context, in dto.CreateUser) (user dto.User, err error) {
	logger := log.Ctx(ctx).With().Str("service", "Users").Str("method", "createUser").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "users.createUser",
				"request":  viewer.Sprintf("%+v", requestUsersCreateUser{In: in}),
				"response": viewer.Sprintf("%+v", responseUsersCreateUser{User: user}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call createUser")
			return
		}
		logger.Info().Func(logHandle).Msg("call createUser")
	}(time.Now())
	return m.next.CreateUser(ctx, in)
}

func (m loggerUsers) UpdateUser(ctx context.Context, id int64, in dto.UpdateUser) (user dto.User, err error) {
	logger := log.Ctx(ctx).With().Str("service", "Users").Str("method", "updateUser").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method": "users.updateUser",
				"request": viewer.Sprintf("%+v", requestUsersUpdateUser{
					Id: id,
					In: in,
				}),
				"response": viewer.Sprintf("%+v", responseUsersUpdateUser{User: user}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call updateUser")
			return
		}
		logger.Info().Func(logHandle).Msg("call updateUser")
	}(time.Now())
	return m.next.UpdateUser(ctx, id, in)
}

func (m loggerUsers) DeleteUser(ctx context.Context, id int64) (err error) {
	logger := log.Ctx(ctx).With().Str("service", "Users").Str("method", "deleteUser").Logger()
	defer func(_begin time.Time) {
		logHandle := func(ev *zerolog.Event) {
			fields := map[string]interface{}{
				"method":   "users.deleteUser",
				"request":  viewer.Sprintf("%+v", requestUsersDeleteUser{Id: id}),
				"response": viewer.Sprintf("%+v", responseUsersDeleteUser{}),
			}
			ev.Fields(fields).Str("took", time.Since(_begin).String())
		}
		if err != nil {
			logger.Error().Err(err).Func(logHandle).Msg("call deleteUser")
			return
		}
		logger.Info().Func(logHandle).Msg("call deleteUser")
	}(time.Now())
	return m.next.DeleteUser(ctx, id)
}
