// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package db

import (
	"context"
)

const createDevice = `-- name: CreateDevice :execlastid
INSERT INTO devices (name, mqtt_topic, device_type, unit, is_active)
VALUES (?, ?, ?, ?, ?)
`

type CreateDeviceParams struct {
	Name       string `json:"name"`
	MqttTopic  string `json:"mqtt_topic"`
	DeviceType string `json:"device_type"`
	Unit       string `json:"unit"`
	IsActive   bool   `json:"is_active"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createDevice,
		arg.Name,
		arg.MqttTopic,
		arg.DeviceType,
		arg.Unit,
		arg.IsActive,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteDevice = `-- name: DeleteDevice :execrows
DELETE FROM devices
WHERE id = ?
`

func (q *Queries) DeleteDevice(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDevice, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDevice = `-- name: GetDevice :one
SELECT id, name, mqtt_topic, device_type, unit, is_active, created_at
FROM devices
WHERE id = ?
`

func (q *Queries) GetDevice(ctx context.Context, id int64) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MqttTopic,
		&i.DeviceType,
		&i.Unit,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, name, mqtt_topic, device_type, unit, is_active, created_at
FROM devices
ORDER BY id
`

func (q *Queries) ListDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MqttTopic,
			&i.DeviceType,
			&i.Unit,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDevice = `-- name: UpdateDevice :execrows
UPDATE devices
SET name = ?, mqtt_topic = ?, device_type = ?, unit = ?, is_active = ?
WHERE id = ?
`

type UpdateDeviceParams struct {
	Name       string `json:"name"`
	MqttTopic  string `json:"mqtt_topic"`
	DeviceType string `json:"device_type"`
	Unit       string `json:"unit"`
	IsActive   bool   `json:"is_active"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDevice,
		arg.Name,
		arg.MqttTopic,
		arg.DeviceType,
		arg.Unit,
		arg.IsActive,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
