// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :execlastid
INSERT INTO users (
    login,
    last_name,
    first_name,
    second_name,
    email,
    phone,
    password_hash,
    is_active
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	Login        string `json:"login"`
	LastName     string `json:"last_name"`
	FirstName    string `json:"first_name"`
	SecondName   string `json:"second_name"`
	Email        string `json:"email"`
	Phone        string `json:"phone"`
	PasswordHash string `json:"password_hash"`
	IsActive     bool   `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createUser,
		arg.Login,
		arg.LastName,
		arg.FirstName,
		arg.SecondName,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.IsActive,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUser = `-- name: GetUser :one
SELECT
    id,
    login,
    last_name,
    first_name,
    second_name,
    email,
    phone,
    last_auth_at,
    is_active
FROM users
WHERE id = ?
`

type GetUserRow struct {
	ID         int64   `json:"id"`
	Login      string  `json:"login"`
	LastName   string  `json:"last_name"`
	FirstName  string  `json:"first_name"`
	SecondName string  `json:"second_name"`
	Email      string  `json:"email"`
	Phone      string  `json:"phone"`
	LastAuthAt *string `json:"last_auth_at"`
	IsActive   bool    `json:"is_active"`
}

func (q *Queries) GetUser(ctx context.Context, id int64) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.LastName,
		&i.FirstName,
		&i.SecondName,
		&i.Email,
		&i.Phone,
		&i.LastAuthAt,
		&i.IsActive,
	)
	return i, err
}

const getUserForAuth = `-- name: GetUserForAuth :one
SELECT
    id,
    login,
    last_name,
    first_name,
    second_name,
    email,
    phone,
    password_hash,
    last_auth_at,
    is_active
FROM users
WHERE login = ?
LIMIT 1
`

type GetUserForAuthRow struct {
	ID           int64   `json:"id"`
	Login        string  `json:"login"`
	LastName     string  `json:"last_name"`
	FirstName    string  `json:"first_name"`
	SecondName   string  `json:"second_name"`
	Email        string  `json:"email"`
	Phone        string  `json:"phone"`
	PasswordHash string  `json:"password_hash"`
	LastAuthAt   *string `json:"last_auth_at"`
	IsActive     bool    `json:"is_active"`
}

func (q *Queries) GetUserForAuth(ctx context.Context, login string) (GetUserForAuthRow, error) {
	row := q.db.QueryRowContext(ctx, getUserForAuth, login)
	var i GetUserForAuthRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.LastName,
		&i.FirstName,
		&i.SecondName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.LastAuthAt,
		&i.IsActive,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    id,
    login,
    last_name,
    first_name,
    second_name,
    email,
    phone,
    last_auth_at,
    is_active
FROM users
ORDER BY id
`

type ListUsersRow struct {
	ID         int64   `json:"id"`
	Login      string  `json:"login"`
	LastName   string  `json:"last_name"`
	FirstName  string  `json:"first_name"`
	SecondName string  `json:"second_name"`
	Email      string  `json:"email"`
	Phone      string  `json:"phone"`
	LastAuthAt *string `json:"last_auth_at"`
	IsActive   bool    `json:"is_active"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Login,
			&i.LastName,
			&i.FirstName,
			&i.SecondName,
			&i.Email,
			&i.Phone,
			&i.LastAuthAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserPassword = `-- name: SetUserPassword :execrows
UPDATE users
SET password_hash = ?
WHERE id = ?
`

type SetUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setUserPassword, arg.PasswordHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchLastAuth = `-- name: TouchLastAuth :execrows
UPDATE users
SET last_auth_at = ?
WHERE id = ?
`

type TouchLastAuthParams struct {
	LastAuthAt *string `json:"last_auth_at"`
	ID         int64   `json:"id"`
}

func (q *Queries) TouchLastAuth(ctx context.Context, arg TouchLastAuthParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchLastAuth, arg.LastAuthAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUser = `-- name: UpdateUser :execrows
UPDATE users
SET
    login = ?,
    last_name = ?,
    first_name = ?,
    second_name = ?,
    email = ?,
    phone = ?,
    is_active = ?
WHERE id = ?
`

type UpdateUserParams struct {
	Login      string `json:"login"`
	LastName   string `json:"last_name"`
	FirstName  string `json:"first_name"`
	SecondName string `json:"second_name"`
	Email      string `json:"email"`
	Phone      string `json:"phone"`
	IsActive   bool   `json:"is_active"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUser,
		arg.Login,
		arg.LastName,
		arg.FirstName,
		arg.SecondName,
		arg.Email,
		arg.Phone,
		arg.IsActive,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
